name: Build CLI
on: [push, pull_request]
jobs:
  build-cli:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Golang
      uses: actions/setup-go@v2
    - name: Install Task
      uses: arduino/setup-task@v1
    - name: Run CI Task
      run: task ci