name: Build CLI
on: [push, pull_request]
jobs:
  build-cli:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Golang
      uses: actions/setup-go@v2
    - name: Get dependencies
        run: |
          go get -u golang.org/x/lint/golint
          go get -v -t -d ./...
